services:
  - type: web
    name: sky-api
    runtime: node
    plan: free
    buildCommand: npm install --prefix backend/admin-panel
    startCommand: npm start --prefix backend/admin-panel
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: https://sky-backend-xisk.onrender.com
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    healthCheckPath: /api/health
